spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/aifitness?useSSL=false&serverTimezone=UTC
    username: root
    password: fauxia765
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
